#!/bin/bash



while true
do
status=`curl 10.8.0.3:9101/metrics 2> /dev/null | grep "aptos_state_sync_version" | grep -v "^#" | grep "{type=\"synced\"}" |awk '{print $2}'`
echo "`date` - $status"
sleep 60
done
